import type { CSSProperties } from "react";

export const s = {
  footer: { display: "flex", gap: 10, justifyContent: "flex-end" } satisfies CSSProperties,
  body: { padding: 24 } satisfies CSSProperties,
  filePicker: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  fileLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    padding: "8px 16px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 14,
    color: "var(--text-primary)",
    userSelect: "none",
  } satisfies CSSProperties,
  fileName: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--err, #ef4444)" } satisfies CSSProperties,
  preview: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  trustWarning: {
    padding: "10px 14px",
    borderRadius: 7,
    background: "var(--warn-bg, #fef3c7)",
    color: "var(--warn-text, #92400e)",
    fontSize: 13,
    lineHeight: 1.5,
    border: "1px solid var(--warn-border, #fcd34d)",
  } satisfies CSSProperties,
  previewMeta: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  droppedSection: { display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  droppedLabel: { fontSize: 12, fontWeight: 600, color: "var(--text-muted)" } satisfies CSSProperties,
  droppedList: { margin: 0, paddingLeft: 18, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  droppedItem: {} satisfies CSSProperties,
  bodySection: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  bodyLabel: { fontSize: 12, fontWeight: 600, color: "var(--text-muted)" } satisfies CSSProperties,
  bodyBox: {
    padding: "12px 16px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    maxHeight: 320,
    overflowY: "auto",
    fontSize: 13,
  } satisfies CSSProperties,
} as const;
