import type { CSSProperties } from "react";

export const s = {
  header: { marginBottom: 20 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700, marginBottom: 6 } satisfies CSSProperties,
  count: { fontWeight: 400, color: "var(--text-muted)" } satisfies CSSProperties,
  caption: { fontSize: 13, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 16px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  note: { flex: 1, fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  date: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  diffOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
  } satisfies CSSProperties,
  diffPanel: {
    background: "var(--bg-surface)",
    borderRadius: 10,
    padding: 24,
    width: "90vw",
    maxWidth: 1000,
    maxHeight: "85vh",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  diffHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: 14,
  } satisfies CSSProperties,
  diffCols: { display: "flex", gap: 16, flex: 1, overflow: "hidden" } satisfies CSSProperties,
  diffCol: { flex: 1, display: "flex", flexDirection: "column", gap: 6, overflow: "hidden" } satisfies CSSProperties,
  diffColLabel: { fontSize: 12, fontWeight: 600, color: "var(--text-muted)" } satisfies CSSProperties,
  diffBody: {
    flex: 1,
    overflow: "auto",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
    padding: "12px 14px",
  } satisfies CSSProperties,
  pre: { margin: 0, fontSize: 12, lineHeight: 1.6, fontFamily: "var(--font-mono, monospace)", whiteSpace: "pre-wrap" } satisfies CSSProperties,
} as const;
