import type { CSSProperties } from "react";

export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1200, margin: "0 auto" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 14, marginBottom: 20 } satisfies CSSProperties,
  headerText: { flex: 1 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  subtitle: { fontSize: 14, color: "var(--text-secondary)", marginTop: 4 } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 200,
  } satisfies CSSProperties,
  searchIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  layout: { display: "flex", gap: 24 } satisfies CSSProperties,
  listCol: { flex: "0 0 380px", minWidth: 0 } satisfies CSSProperties,
  previewCol: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  previewPanel: {
    padding: 20,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    position: "sticky",
    top: 24,
  } satisfies CSSProperties,
  previewHeader: { display: "flex", alignItems: "center", marginBottom: 6 } satisfies CSSProperties,
  previewName: { fontSize: 16, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  previewCaption: { fontSize: 12, color: "var(--text-muted)", marginBottom: 14 } satisfies CSSProperties,
  previewBody: {
    maxHeight: 500,
    overflowY: "auto",
    fontSize: 13,
    lineHeight: 1.6,
  } satisfies CSSProperties,
  previewEmpty: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 200,
    borderRadius: 10,
    border: "1px dashed var(--border)",
  } satisfies CSSProperties,
  previewEmptyText: { fontSize: 14, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
